# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitartabs', '0002_auto_20160803_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
