# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitartabs', '0003_auto_20160803_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
