# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitartabs', '0004_song_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist_slug',
            field=models.SlugField(),
        ),
    ]
