# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitartabs', '0005_auto_20160803_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_slug', models.SlugField()),
                ('songs', models.ManyToManyField(to='guitartabs.Song')),
            ],
        ),
    ]
